name: CI

on:
  push:
    branches:
      - ci-learning
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install erlang and elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28.3.1"
          elixir-version: "1.19.5-otp-28"

      - run: mix --version